# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LineChartDentalStats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LineChartDentalStats
  pod 'Alamofire'
  pod 'SteviaLayout', '4.5.0'

  target 'LineChartDentalStatsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OHHTTPStubs/Swift'
    pod 'OHHTTPStubs'
  end

end
